### PR TITLE
Keyboard command reference

### PR DESCRIPTION
**Pull request by hansfilipelo**

### CODE REVIEW

**Comment by Isakwiberg** [comment]
I think we should maybe let the tweak bar be enabled upon launch to show new users more info. What do you think?

**Comment by hansfilipelo** [comment]
I disagree - but in my view we could add a debugg option that enables it by default.

**Comment by Isakwiberg** [comment]
Ok let's leave it the way it is. Would you like to add anything @lragnarsson ?

**Comment by lragnarsson** [comment]
Looks good!

**Pull request merged**
