### PR TITLE
Windowed mode out of makefile

### PR DESCRIPTION
**Pull request by hansfilipelo**
I got tired of us always changing the screen resolution in the makefile. This PR adds the following: 

- If running "make" then emerald will default to your current screen size
- If setting DEVELOP (`export DEVELOP=1`) in shell before running make (once per shell) emerald will compile with 1024x600 resolution
- When running emerald there are new command line arguments: 

```
-f, --fullscreen        Run emerald in fullscreen
-sf, --scene-file       Choose scene file for emerald
```

### CODE REVIEW

**Comment by lragnarsson** [comment]
Nice one.
But might get annoying to export the environment variable instead?
What about having different make targets? You can have common flags then dev flags and non dev flags like their respective resolution. Just a thought.

**Comment by hansfilipelo** [comment]
One could just set the line in .bashrc / .bash_profile (like I have) if you don't wan't to set it for every shell. You can also set the resolution as shell variable there. 

I can't see why a "release" of Emerald would compile to anything but the screeen resolution by default. It is impossible to make resolution scaling after compile stage without rewriting how we handle shaders.

**Comment by hansfilipelo** [comment]
I should probably name the variables something like "emerald_develop" or something like that.

**Comment by hansfilipelo** [comment]
I've thought about this and I think environment variables is the best way to go here unless we want to rewrite our shader pre-compile-stage to run during Emerald runtime instead of at compile time. 

Until then i think this will have to do. Changed the variables. I removed "DEVELOP" and are now only using this within my ~/.bash_profile: 

```
export EMERALD_SCREEN_WIDTH="SCREEN_WIDTH=1280"
export EMERALD_SCREEN_HEIGHT="SCREEN_HEIGHT=800"
```

I suggest we merge this so that we can have user-independent config - and a default which compiles to screen res.

**Comment by Isakwiberg** [comment]
The window size gets the size of both my monitors together when I have not exported the env variables. Do you think this can be fixed easily? 

Wouldn't it be nice to set the width with a command line argument? 
Like
```
./emerald -w 1280 800
```

**Comment by hansfilipelo** [comment]
"Eyefinity" support 😂 I'll look into this - I assume the problem is on Mac OS since I have dual-monitors on My Linux system.

We use screen size information in shaders which are prepended in pre-compile stage running when you type make. I could rebuild this so that the pre-compile stage for shaders is done at emerald run-time. There's however some ammount of work for this to be Done - bot not impossible at all.

**Comment by hansfilipelo** [comment]
@Isakwiberg Non fix on multi-monitor problems on OS X due to this bug: https://bugzilla.libsdl.org/show_bug.cgi?id=2479

**Pull request merged**
