### PR TITLE
Project specification proposal

### PR DESCRIPTION
**Pull request by hansfilipelo**

### CODE REVIEW

**Comment by Isakwiberg** [comment]
Maybe remove refractions and change reflections to Screen Space Reflections? Looking good otherwise.

**Comment by hansfilipelo** [comment]
Changed as requested.

**Comment by lragnarsson** [comment]
Looks good! Some thoughts: 
Sort participants by last name. If we are listing libraries like SDL2 and glm maybe add assimp and glew as well? And mention C++ as main language.

Edit: assimp is the model loader.

**Comment by hansfilipelo** [comment]
What do you guys think of the name?

**Comment by Isakwiberg** [comment]
It's a great name!

**Comment by lragnarsson** [comment]
Maybe not needed but maybe mention OpenGL and possible version 3.2+ ?

**Pull request merged**
