### PR TITLE
Allows terrain to load heightmaps with 8, 16, 24 or 32-bit PNGs

### PR DESCRIPTION
**Pull request by hansfilipelo**
- Can load any PNG as heightmap, not just fixed-bitlength
- Removed compiler warning in Renderer

To test this, Google "png heightmap" and choose any image to save as res/models/terrain/heightmap.png and load a scene file with terrain. 

If you choose an image larger than 400x400 - remember to increase the chunksize or you will run out of memory.

### CODE REVIEW

**Comment by hansfilipelo** [comment]
Found bug in image loader. I'll look into this.

**Comment by hansfilipelo** [comment]
Seems to work now. Addition: Toggle movement speed with Left shift.

**Comment by lragnarsson** [comment]
There must be something wrong with the high memory usage. When did we go from 400 mb to gigabytes in RAM? Is the duplicate texture loading not fixed because it seems to scale with number of patches?

**Comment by lragnarsson** [comment]
NVM I'm an idiot :+1:

**Pull request merged**
