### PR TITLE
Animation paths and no vsync

### PR DESCRIPTION
**Pull request by hansfilipelo**
This branch adds: 
- Animation paths
- Loader can load animation paths
- Loader uses pipe as an invisible separator in the file for easier-to-read scene files
- vsync is disabled (currently only tested on linux)
- Fixes bug with FPS counter (timediff close to 0) which caused crashes on faster systems

### CODE REVIEW

**Comment by hansfilipelo** [comment]
This probably closes issue #41 right?

**Comment by lragnarsson** [comment]
I don't know if we should fix it in this branch or a separate one but the way we create and manage Animation_Paths, Models and Lights feels odd. If we create objects which goes out of scope they will leave null pointers in the static vector keeping track of all instances.

Maybe we can have vectors of instances as before instead and pass around a pointer to the vector itself?

**Comment by hansfilipelo** [comment]
That’s better than what we do now :)

**Comment by lragnarsson** [comment]
I can try to change it!

**Comment by lragnarsson** [comment]
On second thought. Let's leave such a refactoring to a separate branch!

**Pull request merged**
